model = "gpt-5.3-codex"
personality = "pragmatic"
model_reasoning_effort = "medium"

[mcp_servers.next-devtools]
command = "npx"
args = ["-y", "next-devtools-mcp@latest"]

[mcp_servers.prisma-local]
command = "npx"
args = ["-y", "prisma", "mcp"]

[mcp_servers.prisma-remote]
url = "https://mcp.prisma.io/mcp"

[mcp_servers.mui-mcp]
command = "npx"
args = ["-y", "@mui/mcp@latest"]
